### ISSUE TITLE
Security: remove password from environment variables

### ISSUE THREAD

**Issue by ours-code** [xBrowserSync/API#11]
Hello,

First of all, a big thank you for providing this solution which helps all the orphans of xmarks :)

Would it be possible to make a version of the API with the DB creds put in some file rather than in the environment variables so we can set the access to the relevant process only ?

Cheers to you guys,

**Comment by ly2314** [comment]
You can write your db credentials into config/settings.json

**Comment by ours-code** [comment]
I was following the readme hence I thought the 2 were required in order for the API server to work.
Great, thank you for that fast response !
