### ISSUE TITLE
Docker install please

### ISSUE THREAD

**Issue by gerroon** [xbrowsersync/api#15]
Hi

It would be nice if you offer Docker install, I think if you want large numbers of adaptations the installation should be a bit easier.

thanks

**Comment by mng-au** [comment]
If you guys don't mind my shameless plug 😏. I uploaded my docker-compose setup to <https://github.com/mng-au/docker-xBrowserSync-api>. Hope this will help someone 👍.

**Comment by nero120** [comment]
Nice work @mng-au!

I have prepared a dockerfile to provision just the api as a container and a docker compose file that will provision a production-ready api with db, web server and ssh certs. I'll be releasing them shortly and my plan is to move [api.xbrowsersync.org](https://api.xbrowsersync.org/) into a containerised environment using the same docker compose file.

Hopefully then, anyone who wants to stand up a fully configured, production ready xBrowserSync service can do so with zero config. I'll respond here once it's ready to go.

**Comment by NachoParra** [comment]
Hi,

I also have created my own docker image that you can compile by yourself in which you will have the mongodb initialized & started so you can hear on the port 28080:

[docker-xBrowserSync-api](https://github.com/NachoParra/docker-xBrowserSync-api)

Here you can also get the basic settings file and the commands to compile & run the image.

If you need to run this behind a nginx as reverse proxy, please add the following lines on the nginx confi file 

```
location /xbrowsersync/ {
    auth_basic off;
    rewrite ^/xbrowsersync(/.*)$ $1 break;
    proxy_pass  http://192.168.1.175:28080/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect    off;
}
```

**Comment by mng-au** [comment]
> 
> 
> Nice work @mng-au!
> 
> I have prepared a dockerfile to provision just the api as a container and a docker compose file that will provision a production-ready api with db, web server and ssh certs. I'll be releasing them shortly and my plan is to move [api.xbrowsersync.org](https://api.xbrowsersync.org/) into a containerised environment using the same docker compose file.
> 
> Hopefully then, anyone who wants to stand up a fully configured, production ready xBrowserSync service can do so with zero config. I'll respond here once it's ready to go.

I think a reverse proxy like [Traefik](https://hub.docker.com/_/traefik/) will simplify SSL support. I will update my repo to include traefik for demo when possible.

**Comment by nero120** [comment]
> I think a reverse proxy like Traefik will simplify SSL support. I will update my repo to include traefik for demo when possible.

@mng-au I've been testing Traefik and it's great! Thanks for the suggestion, it's much cleaner than configuring an nginx container with certbot! I'll release my docker files shortly as I think they're ready for distribution now.

**Comment by mng-au** [comment]
> 
> 
> > I think a reverse proxy like Traefik will simplify SSL support. I will update my repo to include traefik for demo when possible.
> 
> @mng-au I've been testing Traefik and it's great! Thanks for the suggestion, it's much cleaner than configuring an nginx container with certbot! I'll release my docker files shortly as I think they're ready for distribution now.

Good to know it's helping you. My bad, I thought I will have the time to update the sample 😂 but it has been 2 weeks already... OMG 😂 I will try the docker files when available 👍

**Comment by ZetaoYang** [comment]
@nero120 Already one week. :joy:

**Comment by nero120** [comment]
Apologies for the long wait (new babies and sick wives have to come before FOSS projects!) but I've managed to finish the Docker configuration for running an xBrowserSync API. You can grab the image on hub.docker.com here:

https://hub.docker.com/r/xbrowsersync/api

I've also included in the [api-docker](https://github.com/xbrowsersync/api-docker/) GitHub repo the required [docker-compose](https://docs.docker.com/compose/) files for orchestrating a complete production-ready SSL-secured xBrowserSync service, including a fully configured MongoDB database container and a [traefik](https://traefik.io/) reverse proxy.

Do let me know if you find any immediate issues, otherwise you can log anything you find in future in the [Issues list](https://github.com/xbrowsersync/api-docker/issues) in the [api-docker](https://github.com/xbrowsersync/api-docker/) GitHub repo.

Have fun and Merry Christmas! 🎄

**Comment by ZetaoYang** [comment]
@nero120 Thanks, that's wonderful!
