### ISSUE TITLE
mongoose client attempting to connect to username

### ISSUE THREAD

**Issue by tlindsay42** [xbrowsersync/api#16]
```bash
$ node dist/api.js
{"name":"xBrowserSync_api","hostname":"[redacted]","pid":8532,"level":50,"req":null,"err":{"message":"failed to connect to server [xbrowsersyncdb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND xbrowsersyncdb xbrowsersyncdb:27017]","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [xbrowsersyncdb:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND xbrowsersyncdb xbrowsersyncdb:27017]\n    at Pool.<anonymous> (/opt/xBrowserSync/api/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:564:11)\n    at Pool.emit (events.js:182:13)\n    at Connection.<anonymous> (/opt/xBrowserSync/api/node_modules/mongoose/node_modules/mongodb-core/lib/connection/pool.js:317:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Socket.<anonymous> (/opt/xBrowserSync/api/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:246:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)"},"msg":"Database error","time":"2018-12-28T17:10:39.969Z","v":0}
{"name":"xBrowserSync_api","hostname":"[redacted]","pid":8532,"level":50,"req":null,"err":{"message":"Unable to connect to database.","name":"Error","stack":"Error: Unable to connect to database.\n    at NativeConnection.dbConn.on (/opt/xBrowserSync/api/dist/core/db.js:66:28)\n    at NativeConnection.emit (events.js:182:13)\n    at process.nextTick (/opt/xBrowserSync/api/node_modules/mongoose/lib/connection.js:575:37)\n    at process._tickCallback (internal/process/next_tick.js:61:11)"},"msg":"Service failed to start","time":"2018-12-28T17:10:39.970Z","v":0}
```

I figured out that this was because my password included incompatible special characters for a URL: `: # ? / \ %`.

Added a note to the readme to help other users and pull request following momentarily.

**Comment by tlindsay42** [comment]
Hey @nero120, just saw a note on MongoDB Atlas that URL encoding the password should fix the issue permanently, so no need to merge the workaround note PR.  Agreed?

![image](https://user-images.githubusercontent.com/11078689/50554217-43886100-0c7c-11e9-8aff-57c664eb868c.png)

**Comment by nero120** [comment]
Agreed. I'm actually just testing different ways of creating the mongoose connection to see if I can avoid putting the username and password in the connection uri. This is what I used to do but for some reason I had issues with docker, so I'm seeing if I can resolve that now. If I can't then I'll do as you suggest and encode.

**Comment by nero120** [comment]
> I'm actually just testing different ways of creating the mongoose connection to see if I can avoid putting the username and password in the connection uri.

Didn't work (don't know why but mongoose/mongodb don't seem to use the user/pass values when set in the connection options object rather than directly in the uri) so I'm just escaping the username and password in the uri instead.
