### ISSUE TITLE
Bookmark URL truncation updates fail

### ISSUE THREAD

**Issue by tlindsay42** [xbrowsersync/api#19]
Noticed that when I attempt to update the URL of a previously saved bookmark, it consistently fails to update if it is a subset of the existing URL (eg: https://github.com/tlindsay42 -> https://github.com/tlindsay4).

Error message: `URL has already been bookmarked`

![image](https://user-images.githubusercontent.com/11078689/50540025-db3c6100-0b4f-11e9-8469-aaf9b10c8f3c.png)

Workaround: Insert a character into the base string so that it is no longer matches the parent and then update it again to the desired URL (eg: https://github.com/tlindsay42 -> https://g*r*ithub.com/tlindsay4 -> https://github.com/tlindsay4).

**Comment by nero120** [comment]
Thanks @tlindsay42, as this is a client issue could you please re-open in the [app issues](https://github.com/xBrowserSync/App/issues/) list? Cheers! 🙏

**Comment by tlindsay42** [comment]
Whoops!  Just found that https://github.com/xbrowsersync/app/issues/62 has already been opened for this one.  Thanks @nero120!.

**Comment by nero120** [comment]
Ah yes! Thanks mate.
