### ISSUE TITLE
Support for MongoDB 3.6+ DNS Seedlist Connection Format (SRV)

### ISSUE THREAD

**Issue by tlindsay42** [xbrowsersync/api#20]
reference: https://docs.mongodb.com/manual/reference/connection-string/

It would be nice to have an option for using either the standard or new MongoDB DNS Seedlist Connection Format.  Per the documentation, the key benefit is:

> Using DNS to construct the available servers list allows more flexibility of deployment and the ability to change the servers in rotation without reconfiguring clients.

The simple workaround is to update the connection string in [src/core/db.ts](https://github.com/xbrowsersync/api/blob/8fddfc9e1279f072c69931a391375e10d4648832/src/core/db.ts#L53), but it would be nice to have a Boolean option in settings.json.

**Comment by nero120** [comment]
@tlindsay42 I can't seem to find any info on docs.mongodb.com specifying the complete list of url options for a seedlist connection string. If you have an environment set up for this, can you tell if this is a valid connection string format:

```
mongodb+srv://mongodb.myhost.com/xbrowsersync?username=xbrowsersyncdb&password=xbrowsersync&authSource=admin
```

Specifically, can I still specify the database name in the connection string, I think username and password are valid as querystring params...

**Comment by tlindsay42** [comment]
If you spin up a dev cluster in MongoDB Atlas, you can test there for free.  I haven't tested DocumentDB just yet.

**Comment by nero120** [comment]
Ah cool, I'll look into it.
