### ISSUE TITLE
dailyNewSyncsLimit or status.allowNewSyncs ?

### ISSUE THREAD

**Issue by swestlake** [xbrowsersync/api#23]
it's difficult to track similar options, the config description is also not too clear between these two settings,

dailyNewSyncsLimit --> setting this to 0 "disables all new syncs", or allows "unlimitted syncs" ?

status.allowNewSyncs  --> I suppose would be the ultimate decider whether 1 new sync is permissible.

There should be added text to dailyNewSyncsLimit's description to clarify that new syncs become possible as long as status.allowNewSyncs is enabled.. 

All the other options look well explained.. and because I think there's lots of them, that I think it's a good idea imho to have vice-versa in both places to remind users to check both settings(as each of these two affects the other).

thanks

**Comment by nero120** [comment]
Thanks @swestlake, hopefully with that commit the explanation of dailyNewSyncsLimit is clearer. To be fair, I could probably just have one option for max number of daily syncs per user, 0 being none and -1 being unlimited. Will think about that for a future release.
