### ISSUE TITLE
Display status.message on the main API service info page

### ISSUE THREAD

**Issue by fantawttw** [xbrowsersync/api#25]
When you visit the main page of the server URL you see a large logo and the text API service info
![image](https://user-images.githubusercontent.com/340697/53506518-068af000-3aae-11e9-8813-7bda4cc0ce41.png)

I would like to suggest that the logo is shrunk and that also the status.message is displayed just under the Status: Online    Version: 1.1.8 part

![image](https://user-images.githubusercontent.com/340697/53506939-e871bf80-3aae-11e9-9e63-bc258c19424c.png)

**Comment by fantawttw** [comment]
Pull request #26 shrinks the logo

**Comment by nero120** [comment]
Good idea, thanks @fantawttw! 😄

**Comment by fantawttw** [comment]
Pull request #27 added to v1.1.9 branch

**Comment by nero120** [comment]
Merged in 2ebf991894282551c837f1a29fc2dd9c428ade79.
