### ISSUE TITLE
How to trigger a sync client side for testing

### ISSUE THREAD

**Issue by ours-code** [xbrowsersync/api#28]
Hello,

Thank you for your work on that project.
I am running a private API and using the latest released client (FF and chrome). To test the sync between my two browser I am searching for a way to trigger a sync (I mean by that fetching new changes) from browser B when I make a change in browser A.
Is there a way to trigger the fetching from the add-ons ? A refresh rate to configure somewhere ? 

Thank you!

**Comment by nero120** [comment]
Hi @ours-code, sorry for the delay in responding. There is a [beta](https://github.com/xbrowsersync/app/releases/tag/v1.5.0beta) currently available which includes the ability to trigger an update manually when available.

Alternatively in the current version (v1.4.0), you'd need to wait up to 15 minutes for the sync to be updated automatically, or manually disable the sync, then re-sync to pick up the changes.
