### ISSUE TITLE
rest api docs?

### ISSUE THREAD

**Issue by nergdron** [xbrowsersync/api#30]
just discovered this project, and seems like exactly what I've been looking for. however, the one thing I can't seem to find is docs for the rest api itself, not just how to setup the server, but what the api looks like so i can write clients for it. is this somewhere other than the code? :)

**Comment by nero120** [comment]
Hi @nergdron, the docs are displayed on the api default page, e.g: https://api.xbrowsersync.org/

**Comment by nergdron** [comment]
Ahhh so simple, nice! maybe just note that in the README.md here? but that's very handy, thanks so much for making this great tool!

**Comment by nero120** [comment]
[Done](https://github.com/xbrowsersync/api/blob/master/README.md#api-documentation).

You're very welcome @nergdron, hope you find it useful! 😄
