### ISSUE TITLE
Interferes with Firefox keyword search

### ISSUE THREAD

**Issue by Amolith** [xbrowsersync/api#31]
I recently discovered that you can `Add a Keyword for this Search` when right-clicking a search box. After defining the keyword, you can type it in the omnibar then your query, press enter, and you're redirected to that site with that search query. It's similar to DuckDuckGo's !bangs but faster and more direct. After setting xBrowserSync up on [my server](https://xsync.nixnet.xyz) and using it for a couple of hours, I noticed that my keywords no longer work even though the bookmarks are there. I'm doing research for a paper right now and I have a lot of academic databases "aliased" to a couple of characters for quick use and not having those is an inconvenience. I'm not sure if a workaround on my part is needed or if a website search feature needs to be added or what but I would really like to see this functionality along with using xBrowserSync.

![image](https://user-images.githubusercontent.com/29460675/65712456-9ca7e880-e086-11e9-9f50-c27e15055324.png)
![image](https://user-images.githubusercontent.com/29460675/65712492-b0534f00-e086-11e9-9d45-1f037cf9c3a1.png)

**Comment by nero120** [comment]
Hi @Amolith, yes unfortunately this particular functionality is dependent on Firefox's native bookmarks keywords, which xBrowserSync cannot sync as [Mozilla have not implemented an API to access them](https://bugzilla.mozilla.org/show_bug.cgi?id=1225916):

![image](https://user-images.githubusercontent.com/4236238/66411740-22fbed00-e9ec-11e9-8eed-081b935a95c5.png)

When performing a "pull" sync, xBrowserSync needs to clear out the local bookmarks before re-populating them which will mean that any native keywords will be lost. Until either Mozilla can implement a keywords API, or I can change xBrowserSync to sync in a non-destructive way (LOT'S of work), there's no fix for this issue unfortunately. Sorry man. 😢

**Comment by Amolith** [comment]
That's unfortunate :confused: I'll keep an eye out to see if they ever release an API. Thanks anyway!
