### ISSUE TITLE
1.1.10 do a backup before using it

### ISSUE THREAD

**Issue by vsatmydynipnet** [xbrowsersync/api#32]
Hi.
updated to 1.1.10 and lost kinda 50% of my bookmarks Firefox 1.5.0. Was able to save booksmarks from one device, now investigating with creating a new sync, but firefox addon says can't connect, but its green when changing the service.

Will report if more details are knows.

**Comment by vsatmydynipnet** [comment]
Update: Testet Chromium + Android and these one works.

**Comment by vsatmydynipnet** [comment]
Firefox 68.1.0esx addon 1.5 can  not create new sync. says can not connect to service. if using an already created one, it only shows kinda the half of the bookmarks. rest is missing.

I will restore the sync server from backup to get it going again.

**Comment by vsatmydynipnet** [comment]
Full server VM restored with 1.1.9. FF connects, creates sync, all fine again. There mus be a bigger problem in 1.1.10.

**Comment by nero120** [comment]
Can you connect/creat a new sync on https://api.xbrowsersync.org?

**Comment by vsatmydynipnet** [comment]
Will test as soon as  i am back to the office. 8:45 am here, will be back ~ 3pm. Will report back. Running  non-standard port on my API server.

**Comment by vsatmydynipnet** [comment]
just stopped and tested. 

Yes, on https://api.xbrowsersync.org it works.

1.1.10 non standard port problem?

**Comment by nero120** [comment]
Yes it could well be a custom port issue. Are you using the docker image?

Also, I have a feeling the loss of bookmarks was an app issue, not api. If you can attach the log to this issue I'll take a look.

**Comment by vsatmydynipnet** [comment]
No I running the API in FreeBSD VM on PROXMOX virtualization. 

I am sorry, i have resetted and recovered server and all systems so  bookmarks are here again. Using 1.1.9 + FF68.1.0+1.5.0 looks ok. Not missing bookmarks at the moment and have a full backup now exportet too.

**Comment by nero120** [comment]
Sorry @vsatmydynipnet, lost track of this issue as have been very busy. Glad you recovered everything. So am I correct in saying that you're running v1.1.9 with a custom port? Are you able to paste your `settings.json` file contents here so I can compare?

**Comment by vsatmydynipnet** [comment]
I still love xbrowsersync :-) Missing 1.5.0 for Android to have the bookmarks synced there to. 1.4.0 cant read my syncs. But it is a real great solution. Thank you for it. Here the settings file, changes hostname.

{
  "allowedOrigins": [],
  "dailyNewSyncsLimit": 3,
  "db": {
    "authSource": "xbrowsersync",
    "connTimeout": 30000,
    "host": "127.0.0.1",
    "name": "myname",
    "username": "myuser",
    "password": "MYPASS",
    "port": 27017
  },
  "log": {
    "enabled": true,
    "level": "info",
    "path": "/var/log/xBrowserSync/api.log",
    "rotatedFilesToKeep": 5,
    "rotationPeriod": "1d"
  },
  "maxSyncs": 5242,
  "maxSyncSize": 4096000,
  "server": {
    "behindProxy": false,
    "host": "xsync.mydomain.tld",
    "https": {
      "certPath": "/usr/home/xbrowsersync/Certs/xsync.mydomain.tld.crt",
      "enabled": true,
      "keyPath": "/usr/home/xbrowsersync/Certs/xsync.mydomain.tld.pem"
    },
    "port":9993
  },
  "status": {
    "allowNewSyncs": true,
    "message": "MY xBrowserSync API v 1.1.9",
    "online": true
  },
  "throttle": {
    "maxRequests": 1000,
    "timeWindow": 300000
  }
}
Running on FreeBSD 11.2-p14 using  1.1.9 at the moment, all fine. Clients: Firefox ESR, Chromium, all on Debian Linux Sid.

**Comment by nero120** [comment]
Ah glad to hear it! Thanks for this, I'll do some local testing based on these settings, see if I can track down the HTTPS/custom port issue.

**Comment by nero120** [comment]
@vsatmydynipnet if you disable https does it connect successfully to the service over http?

**Comment by vsatmydynipnet** [comment]
I am sorry, localhost deas not work because  service is running on an FreeBSD system without desktop. SSH access only.

I have the problem i fully restored 1.1.9 and have overwritten the Proxmox virtual machine. At the moment there is no 1.1.10 running here. Since restoring 1.1.9 all is fine again.

**Comment by nero120** [comment]
@vsatmydynipnet right, I've tested running the api v1.1.10 over HTTPS with a custom port, and everything works as it should for me. Here is my `settings.json`:

```
{
  "db": {
    "host": "127.0.0.1",
    "name": "xbrowsersync",
    "username": "xbssvcacc",
    "password": "TQgcHmFatzPhCQeoJEJ2",
    "port": 27017
  },
  "server": {
    "behindProxy": false,
    "host": "api-https-local.xbrowsersync.org",
    "https": {
      "certPath": "/var/ssl/domain-crt.txt",
      "enabled": true,
      "keyPath": "/var/ssl/domain-key.txt"
    },
    "port": 9993
  }
}
```

So I'm running under a different domain (api-https-local.xbrowsersync.org) but the same port 9993, and the domain api-https-local.xbrowsersync.org is pointing to localhost in my `hosts` file.

If I connect to https://api-https-local.xbrowsersync.org:9993/ in the browser:

![image](https://user-images.githubusercontent.com/4236238/67762784-28be7e80-fa3e-11e9-841c-7fc9213baabc.png)

And in the xBrowserSync v1.5.0 browser extension:

![image](https://user-images.githubusercontent.com/4236238/67762883-51df0f00-fa3e-11e9-8dd7-de2c5827422b.png)

Which works in both Brave (Chromium) and Firefox.

So I can't recreate your issue, and without doing more testing on your setup we're not going to be able to get to the bottom of this unfortunately. I'll close this issue, but if you want to upgrade to v1.1.10 and do some more testing you can respond here. Sorry I couldn't be of more help.

**Comment by vsatmydynipnet** [comment]
Rich, I am under load at the moment. As soon as I et some free time I will try to update to 1.1.10 again to continue testing.  Thank you for your help.

**Comment by vsatmydynipnet** [comment]
I still have this problem with 1.11:

- after I added the first folder and bookmark it deleted around 50% of the bookmarks on firefox.
- trying to create a new sync does not work too
- running 1.11 + syncing it to browsers works, but as soon as 1 folder/bookmark is added i am toasted :-)

Going back to 1.0.9

**Comment by nero120** [comment]
It's not the API, it's an app issue so should be in the app repo. Create an issue there and attach your log file please.

**Comment by vsatmydynipnet** [comment]
I move back to 1.0.9 for now, need to restore my backup on 5 boxes :-)

app worked great till one hour ago with 1.0.9

**Comment by vsatmydynipnet** [comment]
1.1.9 sorry.
- Creating a new sync does not work here too
- connected to an existing sync
- restoring bookmark backup
- waiting for sync to finish so hopefully all systems are ok again
- then will retry to add a folder/bookmark

can you advice how to setup logging in a way it is helpful for you?
-

**Comment by vsatmydynipnet** [comment]
ok, lost, even going back to 1.1.9 fails now. please advise how to setup logging and i will open a issue in ap and remove the addon from my browsers for now.

**Comment by nero120** [comment]
@vsatmydynipnet go to the settings panel and press the download log button!
