### ISSUE TITLE
Need some hand-holding getting started with my docker-compose.yml

### ISSUE THREAD

**Issue by ovizii** [xbrowsersync/api#35]
Hi there,

I have edited and adapted your docker-compose.yml file but before I start posting and explaining it here maybe you can give me a hint how to debug it.

the compose file starts mongo and xbs. mongo runs fine, xbs stops quite fast after starting and "docker logs -f xbs" does not show any log output. 

How can I get some decent log output to debug my problems? 

I noticed the default setting for the log file points to /var/log/xBrowserSync/api.log - shall I mount this file via a docker volume so I can access it after the container stops or is there some other way to get log output?

**Comment by nero120** [comment]
Hi @ovizii, unfortunately I'm not a docker expert so I'm probably not the best person to help in this regard.
