### ISSUE TITLE
status.online = true ignored

### ISSUE THREAD

**Issue by mistergibson** [xbrowsersync/api#37]
I have status.online = true in config/settings.json but when I when I go to the status page it reads offline. Is there a setting elsewhere I'm missing?

If not: I think I found a bug.

I did a fresh git clone from this repo on 2020.01.12 at 8pm PST

It built, it passed all its tests, and it serves up the home page fine. But I cannot figure out HOW to get the service in an ONLINE status. Any clues would be appreciated.

Thanks

**Comment by nero120** [comment]
Can you post the the result of `/info` and your `settings.json` please?

**Comment by mistergibson** [comment]
{"code":"NotImplementedException","message":"The requested route has not been implemented"}

**Comment by nero120** [comment]
Thanks, will do some testing and get back to you.

**Comment by nero120** [comment]
The issue is occurring because you're attempting to run the service on a relative path other than `/`. I've now added support for using relative paths, to resolve the above you'll need to add `server.relativePath` to your `settings.json` with a value of `/xbrowsersync/`.

**Comment by mistergibson** [comment]
Works like a charm now -- thanks so much for making this change :)

**Comment by mistergibson** [comment]
Odd thing: it still says "offline" even though it is indeed online and working -- just thought I'd give you a heads up.

**Comment by nero120** [comment]
No worries @mistergibson, FYI I'll be releasing v1.1.11 shortly once I've updated the docker assets.
