### ISSUE TITLE
buffer.js throw new ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by githlp** [xbrowsersync/api#38]
i followed the instructions on https://github.com/xbrowsersync/api with v1.1.11 but when calling
$ node dist/api.js
i got
` api $ **node dist/api.js**
  buffer.js:327
  **throw new ERR_INVALID_ARG_TYPE**(
  ^

 TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received function hidden
    at Function.from (buffer.js:327:9)
    at fnv1a32 (/home/ronald/xBrowserSync/api/node_modules/mongoose-uuid2/node_modules/bson/lib/bson/fnv1a.js:21:25)
    at fnv1a24 (/home/ronald/xBrowserSync/api/node_modules/mongoose-uuid2/node_modules/bson/lib/bson/fnv1a.js:39:18)
    at Object.<anonymous> (/home/ronald/xBrowserSync/api/node_modules/mongoose-uuid2/node_modules/bson/lib/bson/objectid.js:14:20)
`
What might be the problem ?
$ **node --version
v13.9.0**

$ **mongo --version
MongoDB shell version v4.2.3**
git version: 6874650b362138df74be53d366bbefc321ea32d4
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64

$ **systemctl status mongodb.service**
● mongodb.service - High-performance, schema-free document-oriented database
     Loaded: loaded (/usr/lib/systemd/system/mongodb.service; disabled; vendor preset: disabled)
     Active: active (running) since Sun 2020-02-23 13:01:26 CET; 2h 3min ago
   Main PID: 19482 (mongod)
      Tasks: 32 (limit: 9394)
     Memory: 108.0M
     CGroup: /system.slice/mongodb.service
             └─19482 /usr/bin/mongod --quiet --config /etc/mongodb.conf

Feb 23 13:01:26 ivy3770 systemd[1]: Started High-performance, schema-free document-oriented database.

**Comment by nero120** [comment]
Can you run with node.js 10.x and see if this resolves this issue? I usually target LTS but haven't had time to check under 12.x yet, definitely not 13.x.

**Comment by nero120** [comment]
Closing this as no response from issue opener.

**Comment by zhonghuiwen** [comment]
Yes downgrading to node.js 10 worked, 12 doesn't

**Comment by nero120** [comment]
@zhonghuiwen thanks for confirming, latest release v1.1.13 should run fine on current node.js LTS (14).
