### ISSUE TITLE
private instance

### ISSUE THREAD

**Issue by anibal-aguila** [xbrowsersync/api#42]
Hi, is possible to use it allowing only a certain of users?
thanks in advance,

**Comment by nero120** [comment]
@anibal-aguila not sure what you mean exactly, there are no "users" in the traditional sense, everyone is anonymous. However, some options:

- To prevent access to the server completely, lock down access to a specific IP address/range.
- To prevent "strangers" creating new syncs, you could set the `status.allowNewSyncs` setting to `false`.

Hope that helps.

**Comment by nero120** [comment]
@anibal-aguila not sure what you mean exactly, there are no "users" in the traditional sense, everyone is anonymous. However, some options:

- To prevent access to the server completely, lock down access to a specific IP address/range.
- To prevent "strangers" creating new syncs, you could set the `status.allowNewSyncs` setting to `false`.

Hope that helps.

**Comment by anibal-aguila** [comment]
@nero120 great! that is exactly what I mean.
prevent "strangers" creating new syncs while I can check who the service run.
one more thing, how I can reduce the Update/Sync time?

![image](https://user-images.githubusercontent.com/49025536/79397504-8740d000-7f7e-11ea-86a5-21d6d20bef12.png)

Thanks ;)

**Comment by nero120** [comment]
> how I can reduce the Update/Sync time

Not possible currently, it's fixed at every 15 minutes within the app. There's an existing [feature request](https://github.com/xbrowsersync/app/issues/110) to make it customisable.
