### ISSUE TITLE
node server ignores server.host config key

### ISSUE THREAD

**Issue by julianroetter** [xbrowsersync/api#44]
I set up a self hosted api and it works really good and it is behind a nginx ssl proxy. Port 8080 is not exposed to the internet but I would like to let it only open the port on 127.0.0.1. As described in the documetnation I set up a settings.json in the folder api/config/ with the following content after seeing that the default (127.0.0.1) wasn't used:
[...]`  },
  "server": {
    "host": "127.0.0.1"
 },
`[...]
But still no luck. Any idea why this is happening?
System is ubuntu 20.04 LTS, node v10.19.0, api version 1.5.2

**Comment by nero120** [comment]
@julianroetter actually the `server.host` config setting is kind of redudant, I will likely remove it in the next release. The service always runs on localhost so whatever `server.host` is set to, you should be able to access the service *locally* at `http://127.0.0.1:8080`.

**Comment by julianroetter** [comment]
Thanks for the info. I rebooted the server because I had deactivated ipv6 but that let some other docker containers fail so I just reactivated it and now the node server binds to localhost again. I will close the ticket.
