### ISSUE TITLE
xBrowsersync server space calculation and combination?

### ISSUE THREAD

**Issue by pstein** [xbrowsersync/api#45]
I am interested to sync two (or three) Firefox installations over an xbrowsersync service.

As I read on Home Page all sync servers have a size limit ranging from 1MB up to 12MB.

Since I have a huge bookmark dir tree of approx 7000 bookmarks and (sub)folders this could be critical.
I have no idea how to calculate the necessary size in MB for me.

Are the bookmarks compressed before syncing?
That would use the tiny sync server place much more efficiently.

Could someone tell me how to calc the server space from my given 7000 Bookmarks?

Is there no way to increase the sync server space?

Do I get a warning from the AddOn when my free space approaches limit?

Can I spread my bookmarks over two (!) sync servers?
...or two accounts on the same sync server?

Peter

**Comment by nero120** [comment]
> Are the bookmarks compressed before syncing?

Yes the data is compressed before being encrypted and sent to the server. If at that point you are attempting to sync too much data than the service allows you will get an error.

> Could someone tell me how to calc the server space from my given 7000 Bookmarks?

Not easily!

> Is there no way to increase the sync server space?

If you need more storage then you can either [run your own service](https://github.com/xbrowsersync/api/) or if you [become an xBrowserSync patreon](https://www.patreon.com/xbrowsersync) at the watchdog level then you get access to a private sync service that provides up to 20MB storage.

> Do I get a warning from the AddOn when my free space approaches limit?

No.

> Can I spread my bookmarks over two (!) sync servers?
...or two accounts on the same sync server?

No.

**Comment by m3thm4th** [comment]
@pstein any updates? I also have thousands of bookmarks. I think a rough estimate might be calculated by looking at the `places.sqlite` file, mine is much bigger than any public instance allows (even 20MB is ridiculously low)
