### ISSUE TITLE
Support in Dissenter Browser

### ISSUE THREAD

**Issue by skydiverscott** [xbrowsersync/api#48]
Would like support in the Dissenter browser.  Is this on the road-map?  It is a Chromium based browser so support should be straightforward

**Comment by nero120** [comment]
Hi @skydiverscott, not heard of Dissenter and it's not on the roadmap, though I will check it out as it looks interesting. In any case, I'm only officially planning to support major browsers as every extra browser supported adds more complexity (even if they are chromium based) and therefore more work with every release.

Any minor browser that's chromium-based should work fine with xBrowserSync as-is, unless they have customised certain aspects of the browser API.
