### ISSUE TITLE
Using PM2 css not loaded

### ISSUE THREAD

**Issue by aphe** [xBrowserSync/API#5]
I try to install on my server. the service using pm2, using 127.0.0.1:8080 and create virtualhost so i can access using my subdomain.

but all the css and js not loaded, and return 
`{"code":"ResourceNotFound","message":"/css/bootstrap.min.css"}`
when i try to access directly.

and when i try to change service on the chrome extension the domain became red.

how can i tell the service is working?
the pm2 log show only this
`xBrowserSync-API started on 127.0.0.1:8080 ...`

**Comment by aphe** [comment]
never mind, all i need to change is process.env.XBROWSERSYNC_DB_USER & process.env.XBROWSERSYNC_DB_PWD at the config.js

**Comment by nero120** [comment]
Hi @aphe, glad you solved your issue. I do recommend you run [v1.1.0](https://github.com/xBrowserSync/API/tree/v1.1.0) as the dependencies have been updated and it supports running the service over HTTPS. I'm currently testing before upgrading https://api.xbrowsersync.org and merging to master, but if you do find any issues please raise them here.

**Comment by aphe** [comment]
[v.1.1.0](https://github.com/xBrowserSync/API/tree/v1.1.0) is beautifull.
is there a plan to support browser history as well?

**Comment by nero120** [comment]
> is there a plan to support browser history as well?

It's been requested [here](https://github.com/xBrowserSync/App/issues/13), if it's something you're interested in please do register your feedback on the issue!
