### ISSUE TITLE
Self-Host on SFTP/WebDav

### ISSUE THREAD

**Issue by AbramTTP** [xbrowsersync/api#51]
Hi,

I found this good stuff on PrivacyTools.io but I would love to eventually able to sync my bookmarks and tabs over my own FTP hosted on my own hardware at home.

Do you foresee this to be available in the future? Thank you.

**Comment by nero120** [comment]
It's not out of the question but I would suggest the use-case is not particularly common so is not something I would add to the roadmap. If another dev wanted to implement it then that's fine by me.

The client app will support adding different sync service types (other than the default "xBrowserSync" service) from v1.6.0 (the upcoming release), but I don't plan to add additional sync service types straight away as there are other [major features](https://github.com/xbrowsersync/app/wiki/Roadmap) that are higher priority. Once a few other sync service types have been implemented then it shouldn't be too much of a stretch for a dev to add support for their own preferred method.
