### ISSUE TITLE
Service request limit hit error when syncing

### ISSUE THREAD

**Issue by lancewhit** [xbrowsersync/api#59]
**Describe the issue you are experiencing**
I've been using xBrowserSync for several months with Chrome, Firefox, and Edge, and it's been working smoothly, until now. When I make a bookmark change in one browser, I get the following notification: "Service request limit hit. Sync has been disabled, re-enable Sync to resume syncing." If I then click the toolbar icon for XBrowserSync, I see the same message. But when I check the Data Usage graph, it tells me that I'm using only 21KB out of 1MB, or only 4% of the limit. Is this a server-side glitch or something I need to correct on my end? If the latter, can someone tell me how to resolve this bug? Thanks.

**How can the issue be reproduced?**
Open any browser. Make a change to a bookmark--add or delete. See if error about Service request limit hit appears.

**Screenshots**
If applicable, add screenshots to help explain your problem:

**Desktop browser**
Firefox, Chrome, or Edge

- OS: Windows 10 Pro
- Browser Chrome, Firefox, or Edge
- Version Latest versions of browsers.

![xsync error message 2](https://user-images.githubusercontent.com/2280080/113716396-8ede1500-96b8-11eb-957f-acda5cf2706b.jpg)
![xsync error message 1](https://user-images.githubusercontent.com/2280080/113716397-8ede1500-96b8-11eb-9331-5609b310775a.jpg)

**Comment by nero120** [comment]
@lancewhit I've disabled throttling on the service for the time being, that should hopefully resolve the issue until I can fix the underlying bug. Can you let me know if you still see the issue?

**Comment by lancewhit** [comment]
Thank you. I rebooted my PCs and signed back in. Opened all the browsers, and the syncing is working again with no error message, Looks good at this point. Will let you know if the problem pops up again.

**Comment by nero120** [comment]
I found the culprit! My bad, missed a config step when doing the upgrade to v1.1.13. No bugs to fix so all good now! You shouldn't see this issue anymore but if you do please report back here!

**Comment by lancewhit** [comment]
Great. Thanks for checking and thanks for such a quick response.
