### ISSUE TITLE
xBrowserSync API implementation using Google Cloud Functions

### ISSUE THREAD

**Issue by sbogomolov** [xbrowsersync/api#60]
Hey. I have implemented the minimal subset of the functionality in Google Cloud Functions (with Firestore back-end). If you think it is worth to mention this somewhere, feel free. Here are the relevant repos:

https://github.com/sbogomolov/xbrowsersync-gcf
https://github.com/sbogomolov/xbrowsersync-gcf-terraform

**Comment by nero120** [comment]
This is awesome, thank you @sbogomolov! I've added a link to your implementation repo to the [README](https://github.com/xbrowsersync/api/blob/master/README.md#google-cloud).
