### ISSUE TITLE
Feature request: Support Firefox keyword field

### ISSUE THREAD

**Issue by Maksym-0xp** [xBrowserSync/API#77]
It would be nice if there could be support for additional fields like Firefox's keywords, that let you use bookmarks as "search engines" by entering the keyword followed by a search string.

**Comment by nero120** [comment]
Sadly not possible at this time due to Mozilla's lack of ability to support their own products properly!!

(see [this](https://github.com/xbrowsersync/app/issues/401#issuecomment-1120805837) post for the details)
